name: AICodeBot

on: [push]

# Permissions for the GitHub token.
# This is so the bot can comment on the commit or pull request with the results of the code review.
permissions:
  pull-requests: write
  issues: write
  contents: write

jobs:
  review:
    name: AICodeBot Code Review
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          # Full git history is needed to get a proper list of changed files
          fetch-depth: 0

      - name: AICodeBot Code Review
        uses: gorillamania/AICodeBot-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          aicodebot_personality: "Einstein"
